import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styled, { keyframes } from "styled-components";
import { PieChart, Pie, Sector, Cell, ResponsiveContainer } from "recharts";
import { MAX_WIDTH, md } from "../styles/styles";
import { ReactElement } from "react";

const data = [
    { name: "A1", value: 100 },
    { name: "B1", value: 100 },
    { name: "C1", value: 100 },
    { name: "D1", value: 150 },
];
const COLORS = ["#0088FE", "#00C49F", "#FFBB28", "#FF8042"];
const RADIAN = Math.PI / 180;

const Home: NextPage = () => {
    const router = useRouter();

    const renderCustomizedLabel = ({
        cx,
        cy,
        midAngle,
        innerRadius,
        outerRadius,
        percent,
    }: any): JSX.Element => {
        console.log(cx, cy, percent);
        const radius = innerRadius + (outerRadius - innerRadius) * 0.5;
        const x = cx + radius * Math.cos(-midAngle * RADIAN);
        const y = cy + radius * Math.sin(-midAngle * RADIAN);

        return (
            <text
                x={x}
                y={y}
                fill="white"
                textAnchor={x > cx ? "start" : "end"}
                dominantBaseline="central"
            >
                {`${(percent * 100).toFixed(0)}%`}
            </text>
        );
    };
    return (
        <>
            <Head>
                <title>Adam X Ego</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HeaderWrapper>
                <div className="header">
                    <div className="start">
                        <h2>Logo</h2>
                    </div>
                    <div className="end">
                        <Link href="#about">
                            <a>About</a>
                        </Link>
                        <Link href="#roadmap">
                            <a>Roadmap</a>
                        </Link>
                        <Link href="#gallery">
                            <a>Gallery</a>
                        </Link>
                        <Link href="#team">
                            <a>Team</a>
                        </Link>
                        <div>
                            <select
                                name="lang"
                                id="lang"
                                onChange={({ currentTarget }) => {
                                    const value =
                                        currentTarget.options[currentTarget.selectedIndex].value;
                                    router.push(router.pathname, router.pathname, {
                                        locale: value,
                                    });
                                }}
                            >
                                <option value="ko">KO</option>
                                <option value="en">EN</option>
                            </select>
                        </div>
                    </div>
                </div>
            </HeaderWrapper>

            <MainWrapper>
                <section className="thumbnail-wrapper">
                    <img src="../static/img/main.png" alt="main" />
                </section>
                <section className="arrow-wrapper">
                    <div className="arrow-right">
                        <span className="percentage">00%</span>
                        <div className="img"></div>
                    </div>
                    <div className="arrow-left">
                        <span className="percentage">00%</span>
                        <div className="img" id="about"></div>
                    </div>
                </section>
                <section className="about-wrapper">
                    <div className="about">
                        <div>
                            <p style={{ fontSize: "1.5rem", marginBottom: "1rem" }}>히스토리</p>
                            <p style={{ fontSize: "1.25rem", lineHeight: "1.5" }}>
                                아담이 apple을 한입 베어 무는 순간, 어떤 일이 펼쳐질 지 그는 전혀
                                짐작 하지 못했다. 아담 후손의 ego는 선과 악으로 나뉘었고, 아담은
                                후손들의 ego를 더 이상 컨트롤 할 수 없게 되면서 선과 악을 따르는
                                추종자들의 역사가 시작되었다. 그리고 선과 악의 대립은 결국 전쟁의
                                서사를 쓰게 된다.
                            </p>
                        </div>
                        <div className="img"></div>
                    </div>
                    <div className="about reverse">
                        <div className="img"></div>
                        <div>
                            <p style={{ fontSize: "1.5rem", marginBottom: "1rem" }}>Adam</p>
                            <p style={{ fontSize: "1.25rem", lineHeight: "1.5" }}>
                                576개의 pixel로 이루어지고 고유의 item을 장착한 generative art
                                ‘아담스이고’는 각각 다른 10,000명으로 탄생한 고유의 인물입니다.
                                5,000명의 선한 정체성, 5,000명의 악한 정체성으로 탄생한
                                ‘아담스이고’는 클레이튼 블록체인에서 공식적으로 소유할 수 있습니다.
                                각각의 아담은 착용한 아이템에 따라 레벨이 정해집니다.
                            </p>
                        </div>
                    </div>
                    <div className="about">
                        <div style={{ lineHeight: "1.5" }}>
                            <h1 style={{ marginBottom: "1.5rem" }}>War System</h1>
                            <p style={{ fontSize: "1.25rem", lineHeight: "1.5" }}>
                                - Rule 일정 시간까지 총 volume이 높은 ego team이 승리합니다. 매회
                                배틀이 종료된 뒤 token 응모를 통해 전리품을 얻을 수 있습니다.
                            </p>
                            <p style={{ fontSize: "1.25rem", lineHeight: "1.5" }}>
                                - Token분배 전쟁에 참여하는 1adam당 1apple token 지급
                            </p>
                            <p style={{ fontSize: "1.25rem", lineHeight: "1.5" }}>
                                - Ceremony 우승한 ego team에게 전리품 응모 권한이 생깁니다. 소유한
                                token 최대 갯수만큼 응모할 수 있습니다. (전리품은 매 전쟁 시작전에
                                공지 됩니다.)
                            </p>
                            <p style={{ fontSize: "1.25rem", lineHeight: "1.5" }}>
                                - buyback (커뮤니티 쪽에서 언급) 일정 수량의 nft를 바이백 하여 추후
                                에어드랍으로 증정
                            </p>
                        </div>
                    </div>
                </section>
                <section className="roadmap-wrapper">
                    <h1 style={{ marginBottom: "1rem" }}>Roadmap</h1>
                    <p style={{ marginBottom: "2.5rem", lineHeight: "1.5" }}>
                        Adam x Ego 로드맵은 각 목표 단계에 도달하면 다음 단계를 진행하는 것입니다.
                        <br />
                        또한 장기적인 프로젝트를 목표로 하고 있습니다.
                        <br /> 매 단계마다 목표를 실행하기 위해 ego-team을 구성하세요.
                    </p>
                    <div className="content">
                        <div className="item">
                            <div className="text">
                                <h3>애플토큰</h3>
                                <p>
                                    애플토큰을 활용한 로터리 시스템 개발 애플토큰은 향후 모든
                                    아담스이고 프로젝트에서 사용 될 예정
                                </p>
                            </div>
                        </div>
                        <div className="item">
                            <div className="text">
                                <h3>홀더 우대</h3>
                                <p>홀더 기반 거버넌스 커뮤니티 투표 시스템 개발</p>
                            </div>
                        </div>
                        <div className="item">
                            <div className="text">
                                <h3>기부</h3>
                                <p>매 분기마다 일정 수익을 기부 (단체 정하기)</p>
                            </div>
                        </div>
                        <div className="item">
                            <div className="text">
                                <h3>협업</h3>
                                <p>타 프로젝트 팀과 콜라보 혹은 파트너쉽 체결</p>
                            </div>
                        </div>
                        <div className="item">
                            <div className="text" id="gallery">
                                <h3>V2</h3>
                                <p>버젼 2를 통한 생태계 확장과 글로벌 시장</p>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="gallery-wrapper">
                    <div className="content">
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                        <div className="img"></div>
                    </div>
                </section>
                <section className="chart-wrapper">
                    <div>
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam unde
                        reprehenderit maxime quidem, delectus molestias veniam? Quae odit iure eaque
                        eum autem incidunt aperiam sunt, neque odio illum nemo nobis voluptatem
                        ducimus dolores enim molestiae commodi impedit corrupti non animi alias
                        quidem delectus doloremque accusamus! Temporibus sed voluptates aliquid
                        obcaecati doloribus modi explicabo, facilis soluta consequuntur alias
                        officiis maxime voluptatum possimus assumenda dignissimos est exercitationem
                        nihil animi. Obcaecati nihil ipsa laudantium accusamus sit, rem iste quas,
                        doloribus sunt pariatur dolorum.
                    </div>
                    <ResponsiveContainer width="100%" height="100%" id="team">
                        <PieChart width={400} height={400}>
                            <Pie
                                data={data}
                                dataKey="value"
                                cx="50%"
                                cy="50%"
                                innerRadius={50}
                                outerRadius={90}
                                label={({ percent }) => `TEXT ${(percent * 100).toFixed(0)}%`}
                                labelLine={false}
                            >
                                {data.map((_, index) => (
                                    <Cell
                                        key={`cell-${index}`}
                                        fill={COLORS[index % COLORS.length]}
                                    />
                                ))}
                            </Pie>
                        </PieChart>
                    </ResponsiveContainer>
                </section>
                <section className="team-wrapper">
                    <h1>Team</h1>
                    <div className="content">
                        <div className="profile">
                            <div className="img"></div>
                            <p className="title">
                                <b>Eden</b>
                                <br />
                                <small>Developer</small>
                            </p>
                            {/* <p className="description">
                                adam 캐릭터의 배경이 되었습니다. <br />
                                ntf 수집을 좋아합니다.
                            </p> */}
                        </div>
                        <div className="profile">
                            <div className="img"></div>
                            <p className="title">
                                <b>Dotty</b>
                                <br />
                                <small>Artist</small>
                            </p>
                            {/* <p className="description">
                                미쳤습니다. 괴상한 그의 손가락에선 어떤 것이 나올 지 모릅니다.
                                <br /> 젤리를 좋아합니다.
                            </p> */}
                        </div>
                        <div className="profile">
                            <div className="img"></div>
                            <p className="title">
                                <b>Mada</b>
                                <br />
                                <small>Advisor</small>
                            </p>
                            {/* <p className="description">
                                adam x ego의 고문을 담당합니다.
                                <br /> 정말 고통스럽게 합니다.
                            </p> */}
                        </div>
                        <div className="profile">
                            <div className="img"></div>
                            <p className="title">
                                <b>Gabriel</b>
                                <br />
                                <small>Marketer</small>
                            </p>
                            {/* <p className="description">
                                평화를 좋아합니다. <br />
                                언제나 모든 인류가 평화롭길 원합니다.
                            </p> */}
                        </div>
                        <div className="profile">
                            <div className="img"></div>
                            <p className="title">
                                <b>Lucifer</b>
                                <br />
                                <small>Marketer</small>
                            </p>
                            {/* <p className="description">
                                언제나 악마같은 냉혹함을 토대로 nft, 블록체인 및 실물자산등 투자를
                                전문으로 합니다.
                            </p> */}
                        </div>
                    </div>
                </section>
            </MainWrapper>

            <FooterWrapper>
                <p>
                    Powered by <span>© 2021 Adam X Ego Team. All rights reserved.</span>
                </p>
            </FooterWrapper>
        </>
    );
};

const Fade = keyframes`
    from {
     opacity: 0;   
    }
    to {
        opacity: 1;
    }
`;

const HeaderWrapper = styled.header`
    max-height: 3.75rem;
    width: 100%;

    margin: 0 auto;

    position: fixed;
    z-index: 1;

    background-color: rgba(18, 18, 18, 1);

    ${md} {
        padding: 0 1rem;
    }

    > .header {
        max-width: ${MAX_WIDTH};
        width: 100%;
        height: 3.75rem;

        margin: 0 auto;
        padding: 0 1rem;

        display: flex;
        justify-content: space-between;
        align-items: center;

        ${md} {
            padding: 0;
            margin: 0;
        }

        > div {
            display: inline-flex;
            flex-flow: row nowrap;

            gap: 1.5rem;

            font-size: 1.25rem;

            ${md} {
                font-size: 0.875rem;
                gap: 0.5rem;
            }
        }

        select {
            cursor: pointer;
            border: none;
            outline: none;
            color: #ffffff;
            font-size: 0.975rem;

            line-height: 1.5em;
            padding-right: 1rem;
            display: inline-block;
            background-color: transparent;

            margin: 0;
            box-sizing: border-box;

            ${md} {
                font-size: 0.75rem;
                padding-right: 0.125rem;
                background-color: #ffffff;
                color: #000000;
            }
        }
    }
`;

const MainWrapper = styled.div`
    max-width: ${MAX_WIDTH};
    margin: 0 auto;
    padding-top: 3.75rem;

    ${md} {
        padding: 3.75rem 1rem 0;
    }

    section > h1 {
        margin-bottom: 5rem;
        font-size: 2rem;
        letter-spacing: 0.02rem;

        ${md} {
            margin-bottom: 2rem;
        }
    }

    .thumbnail-wrapper {
        img {
            object-fit: contain;
            width: 100%;
        }
    }

    .arrow-wrapper {
        margin: 3rem 0;
        position: relative;
        display: flex;
        justify-content: space-between;
        min-height: 25rem;

        ${md} {
            flex-flow: column nowrap;
            justify-content: center;
            min-height: 40rem;
        }
        .arrow-right {
            flex: 0 0 30%;
            position: relative;
            display: inline-flex;
            flex-flow: column nowrap;
            gap: 2rem;
            transition: right 0.5s;
            right: 0;

            &:before {
                content: "";
                position: absolute;
                right: 4px;
                top: 15px;
                background-color: #f5c631;
                width: 6px;
                height: 26px;
                transform: rotate(140deg);
                /* transition: right 0.3s; */
                border-radius: 20px;
            }

            &:after {
                content: "";
                position: absolute;
                right: 0;
                top: 33px;
                background-color: #f5c631;
                width: 100%;
                height: 6px;
                /* transition: right 0.3s; */
            }

            .img {
                background: url("https://via.placeholder.com/480") no-repeat center/cover;
                width: 100%;
                height: 100%;
            }

            &:hover {
                right: -5rem;

                .img {
                    background: url("https://via.placeholder.com/480") no-repeat center/cover;
                    animation: ${Fade} 1s linear;
                }
            }

            ${md} {
                flex: 1;
                height: 15rem;

                &:hover {
                    right: 0;
                }
            }
        }
        .arrow-left {
            flex: 0 0 30%;
            position: relative;
            display: inline-flex;
            flex-flow: column nowrap;
            gap: 2rem;
            align-items: flex-end;
            transition: left 0.5s;
            left: 0;

            &:before {
                content: "";
                position: absolute;
                left: 4px;
                top: 15px;
                background-color: #f5c631;
                width: 6px;
                height: 26px;
                transform: rotate(40deg);
                /* transition: left 0.3s; */
                border-radius: 20px;
            }

            &:after {
                content: "";
                position: absolute;
                left: 0;
                top: 33px;
                background-color: #f5c631;
                width: 100%;
                height: 6px;
                /* transition: left 0.3s; */
            }

            .img {
                background: url("https://via.placeholder.com/480") no-repeat center/cover;
                width: 100%;
                height: 100%;
            }

            &:hover {
                left: -5rem;

                .img {
                    background: url("https://via.placeholder.com/480") no-repeat center/cover;
                    animation: ${Fade} 1s linear;
                }
            }

            ${md} {
                flex: 1;
                height: 15rem;
                margin-top: 3rem;

                &:hover {
                    left: 0;
                }
            }
        }

        .percentage {
            font-size: 1.25rem;
            font-weight: bold;
            letter-spacing: 0.01rem;
        }
    }

    .about-wrapper {
        border-top: 1px solid #f5c631;
        padding: 3rem 1.25rem;

        position: relative;

        ${md} {
            padding: 3rem 0;
        }

        .about:not(.reverse) {
            display: grid;
            grid-template-columns: 1fr 19.5rem;
            align-items: center;
            min-height: 20rem;
            gap: 2rem;

            .img {
                background: url("https://via.placeholder.com/312") no-repeat center/cover;
                height: 100%;
            }

            ${md} {
                grid-template-columns: 1fr;
                .img {
                    height: 15rem;
                }
            }

            &:last-child {
                grid-template-columns: 1fr;

                padding: 0 2rem;

                ${md} {
                    padding: 0;
                }
            }
        }

        .reverse {
            display: grid;
            grid-template-columns: 19.5rem 1fr;
            align-items: center;
            min-height: 20rem;
            gap: 2rem;

            .img {
                background: url("https://via.placeholder.com/312") no-repeat center/cover;
                height: 100%;
            }

            ${md} {
                grid-template-columns: 1fr;

                > *:first-child {
                    grid-row: 1;
                }
                .img {
                    grid-row: 2;
                    height: 15rem;
                }
            }
        }

        > * + * {
            margin-top: 4rem;
        }
    }

    .roadmap-wrapper {
        border-top: 1px solid #f5c631;
        padding: 3rem 1.25rem;

        position: relative;

        > .content {
            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
            gap: 1rem;

            .item {
                .img {
                    background: url("https://via.placeholder.com/224") no-repeat center/cover;
                    width: 100%;
                    height: 14rem;

                    margin-bottom: 1rem;
                }

                .text {
                    text-align: center;
                    word-break: keep-all;
                    line-height: 1.5;

                    > h3 {
                        margin-bottom: 1rem;
                    }

                    > p {
                        line-height: 1.5;
                    }
                }
            }

            ${md} {
                grid-template-columns: 1fr;
                gap: 2rem;
            }
        }
        ${md} {
            padding: 3rem 0;
        }
    }

    .gallery-wrapper {
        border-top: 1px solid #f5c631;
        padding: 4rem 1.25rem;

        position: relative;

        .content {
            width: 100%;
            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr;
            gap: 1rem;

            padding: 0 12.5rem;

            .img {
                width: 100%;
                height: 200px;
                background: url("../static/img/sample.png") no-repeat center/contain;
            }
            ${md} {
                grid-template-columns: 1fr 1fr;
                padding: 0 2rem;

                .img {
                    height: 8rem;
                    background: url("../static/img/sample.png") no-repeat center/contain;
                }
            }
        }

        ${md} {
            padding: 4rem 0;
        }
    }

    .chart-wrapper {
        border-top: 1px solid #f5c631;
        padding: 4rem 1.25rem;

        position: relative;

        display: grid;
        grid-template-columns: 1.25fr 0.75fr;
        align-items: center;

        ${md} {
            grid-template-columns: 1fr;
        }

        > div:last-child {
            min-height: 20rem;
        }
    }

    .team-wrapper {
        border-top: 1px solid #f5c631;
        padding: 3rem 1.25rem;

        position: relative;

        ${md} {
            padding: 3rem 0;
        }

        .content {
            width: 100%;
            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
            gap: 1rem;

            ${md} {
                grid-template-columns: 1fr 1fr;
            }
            .profile {
                display: inline-flex;
                flex-flow: column nowrap;
                align-items: center;
                gap: 0.875rem;

                .img {
                    background: url("https://via.placeholder.com/224") no-repeat center/cover;
                    width: 100%;
                    height: 14rem;
                }

                .title {
                    font-size: 1.25rem;
                    text-align: center;
                    ${md} {
                        font-size: 1rem;
                    }
                }

                .description {
                    font-size: 1rem;
                    text-align: center;
                    word-break: keep-all;
                    ${md} {
                        font-size: 0.875rem;
                    }
                }
            }
        }
    }
`;

const FooterWrapper = styled.footer`
    max-width: ${MAX_WIDTH};
    margin: 0 auto;
    text-align: center;
    padding: 3rem 0;

    ${md} {
        padding: 3rem 1rem;
    }
`;

export default Home;
