import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { MAX_WIDTH, md } from "../styles/styles";
import { Twitter } from "../utils/icons";
import { HeaderWrapper, FooterWrapper } from "./index";

const Mint: NextPage = () => {
    const router = useRouter();
    const [{ day, hour, minute, second }, setCountDown] = useState({
        day: "",
        hour: "",
        minute: "",
        second: "",
    });

    // const { day, hour, min, sec } = calcTimeHandler();

    useEffect(() => {
        const calcTick = () => {
            const today = new Date();
            const targetDay = new Date("2022-01-18 20:00:00");

            const gap = targetDay.getTime() - today.getTime();

            const day = Math.ceil(gap / (1000 * 60 * 60 * 24)).toString();
            const hour = Math.floor((gap % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)).toString();
            const minute = Math.ceil((gap % (1000 * 60 * 60)) / (1000 * 60)).toString();
            const second = Math.ceil((gap % (1000 * 60)) / 1000).toString();

            setCountDown({ day, hour, minute, second });
        };
        const interval = setInterval(calcTick, 1000);

        return () => clearInterval(interval);
    }, []);
    return (
        <>
            <Head>
                <title>Adam X Ego</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderWrapper>
                <div className="header">
                    <div className="start">
                        <Link href="/">
                            <a>
                                <h2 className="logo">ADAM X EGO</h2>
                            </a>
                        </Link>
                    </div>
                    <div className="end">
                        <Link href="#about">
                            <a>About</a>
                        </Link>
                        <Link href="#roadmap">
                            <a>Roadmap</a>
                        </Link>
                        <Link href="#gallery">
                            <a>Gallery</a>
                        </Link>
                        <Link href="#team">
                            <a>Team</a>
                        </Link>
                        <Link href="/mint">
                            <a>Mint</a>
                        </Link>
                        <div>
                            <select
                                name="lang"
                                id="lang"
                                onChange={({ currentTarget }) => {
                                    const value =
                                        currentTarget.options[currentTarget.selectedIndex].value;
                                    router.push(router.pathname, router.pathname, {
                                        locale: value,
                                    });
                                }}
                            >
                                <option value="ko">KO</option>
                                <option value="en">EN</option>
                            </select>
                        </div>
                    </div>
                </div>
            </HeaderWrapper>

            <MainWrapper>
                <div className="wrapper">
                    <div id="countdown">
                        <ul>
                            <li>
                                <span id="days">{day}</span>days
                            </li>
                            <li>
                                <span id="hours">{hour}</span>Hours
                            </li>
                            <li>
                                <span id="minutes">{minute}</span>Minutes
                            </li>
                            <li>
                                <span id="seconds">{second}</span>Seconds
                            </li>
                        </ul>
                    </div>
                    <article>
                        <div className="chart">
                            <div className="bar">
                                <div className="face top">
                                    <div className="growing-bar"></div>
                                </div>
                                <div className="face side-0">
                                    <div className="growing-bar"></div>
                                </div>
                                <div className="face floor">
                                    <div className="growing-bar"></div>
                                </div>
                                <div className="face side-a"></div>
                                <div className="face side-b"></div>
                                <div className="face side-1">
                                    <div className="growing-bar"></div>
                                </div>
                            </div>
                        </div>
                    </article>
                    <button>Mint</button>
                </div>
            </MainWrapper>

            <FooterWrapper>
                <p style={{ fontFamily: router.locale === "ko" ? "Nanum Gothic" : "Hind" }}>
                    Powered by <span>© 2021 Adam X Ego Team. All rights reserved.</span>
                </p>
                <p className="icon-container">
                    {/* <Link href="#">
                        <a>
                            <Discord width="1.5rem" height="1.5rem" />
                        </a>
                    </Link>
                    <Link href="#">
                        <a>
                            <Kakaotalk width="1.5rem" height="1.5rem" />
                        </a>
                    </Link> */}
                    <Link href="#">
                        <a href="https://twitter.com/adamxego" target="_blank" rel="noreferrer">
                            <Twitter width="1.5rem" height="1.5rem" />
                        </a>
                    </Link>
                </p>
            </FooterWrapper>
        </>
    );
};

const MainWrapper = styled.div`
    max-width: ${MAX_WIDTH};
    min-height: 100vh;
    margin: 0 auto;
    padding-top: 3.75rem;

    display: flex;
    flex-flow: column nowrap;
    align-items: center;
    justify-content: center;

    ${md} {
        padding: 3.75rem 1rem 0;
    }

    .wrapper {
        max-width: ${MAX_WIDTH};
        width: 100%;

        display: flex;
        flex-flow: column nowrap;
        align-items: center;

        #countdown {
            display: flex;
            justify-content: center;
            margin-bottom: 5rem;

            ${md} {
                margin-bottom: 2rem;
            }
            ul {
                li {
                    display: inline-flex;
                    flex-flow: column nowrap;
                    align-items: center;

                    font-size: 1.5rem;
                    list-style-type: none;
                    padding: 1rem;
                    text-transform: uppercase;

                    ${md} {
                        font-size: 0.625rem;
                    }

                    span {
                        display: block;
                        font-size: 4.5rem;

                        ${md} {
                            font-size: 1.75rem;
                        }
                    }
                }
            }
        }
        article {
            width: 100%;
            margin-bottom: 5rem;

            ${md} {
                margin-bottom: 2rem;
            }
            .chart {
                font-size: 1em;
                perspective: 1000px;
                perspective-origin: 50% 50%;
                -webkit-backface-visibility: visible;
                backface-visibility: visible;

                ${md} {
                    width: 90%;
                    margin: 0 auto;
                }

                .bar {
                    font-size: 1em;
                    position: relative;
                    height: 10em;
                    transition: all 0.3s ease-in-out;
                    transform: rotateX(80deg) rotateY(0deg);
                    transform-style: preserve-3d;

                    ${md} {
                        height: 5rem;
                    }

                    .face {
                        font-size: 3em;
                        position: relative;
                        width: 100%;
                        height: 2em;
                        background-color: rgba(254, 254, 254, 0.3);

                        ${md} {
                            font-size: 1rem;
                            height: 2rem;
                        }

                        &.side-a,
                        &.side-b {
                            width: 2em;
                            ${md} {
                                width: 2rem;
                            }
                        }

                        &.side-a {
                            transform: rotateX(90deg) rotateY(-90deg) translateX(2em)
                                translateY(1em) translateZ(1em);

                            ${md} {
                                transform: rotateX(90deg) rotateY(-90deg) translateX(2rem)
                                    translateY(1rem) translateZ(1rem);
                            }
                        }

                        &.side-b {
                            transform: rotateX(90deg) rotateY(-90deg) translateX(4em)
                                translateY(1em) translateZ(-1em);
                            position: absolute;
                            right: 0;

                            ${md} {
                                transform: rotateX(90deg) rotateY(-90deg) translateX(4rem)
                                    translateY(1rem) translateZ(-1rem);
                            }
                        }

                        &.side-0 {
                            transform: rotateX(90deg) rotateY(0) translateX(0) translateY(1em)
                                translateZ(-1em);

                            ${md} {
                                transform: rotateX(90deg) rotateY(0) translateX(0) translateY(1rem)
                                    translateZ(-1rem);
                            }
                        }

                        &.side-1 {
                            transform: rotateX(90deg) rotateY(0) translateX(0) translateY(1em)
                                translateZ(3em);

                            ${md} {
                                transform: rotateX(90deg) rotateY(0) translateX(0) translateY(1rem)
                                    translateZ(3rem);
                            }
                        }

                        &.top {
                            transform: rotateX(0deg) rotateY(0) translateX(0em) translateY(4em)
                                translateZ(2em);

                            ${md} {
                                transform: rotateX(0deg) rotateY(0) translateX(0em) translateY(4rem)
                                    translateZ(2rem);
                            }
                        }

                        &.floor {
                            box-shadow: 0 0.1em 0.6em rgba(0, 0, 0, 0.3),
                                0.6em -0.5em 3em rgba(0, 0, 0, 0.3), 1em -1em 8em #fefefe;

                            ${md} {
                                box-shadow: 0 0.1rem 0.6rem rgba(0, 0, 0, 0.3),
                                    0.6rem -0.5rem 3rem rgba(0, 0, 0, 0.3), 1rem -1rem 8rem #fefefe;
                            }
                        }

                        .growing-bar {
                            transition: all 0.3s ease-in-out;
                            background-color: rgba(118, 201, 0, 0.6);
                            width: 75%;
                            height: 2em;

                            ${md} {
                                height: 2rem;
                            }
                        }
                    }
                }
            }
        }

        button {
            cursor: pointer;
            max-width: 240px;
            width: 100%;
            min-height: 3rem;
            font-family: "Hide";
            font-size: 2.5rem;

            background-color: transparent;
            border: 0;
            outline: 0;

            color: rgba(255, 255, 255, 1);
            border: 2px solid rgba(255, 255, 255, 1);

            line-height: 2;

            transition: 0.5s ease;

            ${md} {
                max-width: 160px;
                min-height: 2rem;
                font-size: 1.75rem;
                border: 1px solid rgba(255, 255, 255, 1);
            }
            &:hover,
            &:focus {
                border-color: rgba(118, 201, 0, 1);
                color: rgba(118, 201, 0, 1);
            }
        }
    }
`;

export default Mint;
